countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
             "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
             "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil",
             "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde",
             "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", "Cook Islands",
             "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
             "Democratic Republic of Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
             "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland",
             "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea",
             "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran",
             "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
             "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania",
             "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
             "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia (country)", "Moldova", "Mongolia",
             "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
             "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "North Korea", "Norway", "Oman", "Pakistan",
             "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar",
             "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
             "Saint Vincent and the Grenadines", "Samoa", "Sao Tome and Principe", "Saudi Arabia", "Senegal",
             "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
             "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan (former)", "Suriname",
             "Swaziland", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor", "Togo",
             "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine",
             "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
             "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]

res = {'06HONGKONG4795': {'date': {'month': 'DEC', 'year': '2006'},
                          'entity_involved': ['RHMFIUU/HQ', 'USDOC', 'OEA', 'LHINES/DFARROW USDOC', 'FCS',
                                              'the Export Administration Act', 'the Office of Enforcement Analysis',
                                              'the USDOC Bureau of Industry and Security', 'BIS', 'Export Control',
                                              'Advanced Energy-Shenzhen ', 'Baltrans', 'ECCN',
                                              'International Rectifier of Leominster', 'International Rectifier',
                                              'Advanced Energy', 'ECO', 'Airfreight Operations', 'Operations Manager',
                                              'Airfreight', 'Federal Express', "Advanced Energy's", 'BIS '],
                          'from': 'AMCONSUL HONG KONG',
                          'keywords': ['subject', 'ankel', 'providers', 'street', 'route'],
                          'most_common_words': [('Advanced', 14), ('Energy', 14), ('Baltrans', 10), ('Mr.', 10),
                                                ('Lam', 9), ('shipment', 8), ('Hong', 8), ('Kong', 8), ('items', 8),
                                                ('ECO', 6), ('USDOC', 5), ('export', 5), ('OEA', 4), ('provided', 4)],
                          'people_involved': ['RUCPDOC', 'RUEHC', 'SIPDIS ', 'WILLIAM ZARIT ', 'BMGT BEXP', 'ETRD ETTC',
                                              'Philip Ankel', 'Tai Yip Street', 'Theodore Shum', 'Gordon Lam', 'Lam',
                                              'Cunningham'],
                          'place_involved': ['KOWLOON', 'HONG KONG', 'CHINA', 'MASSACHUSETTS', 'UNITED STATES',
                                             'SHENZHEN'],
                          'place_of_document': 'HONGKONG',
                          'subject': 'EXTRANCHECK: POST SHIPMENT VERIFICATION:  ADVANCED ' 'ENERGY-SHENZHEN C/O '
                                     'BALTRANS LOGISTRIC ',
                          'tags': ['BMGT', 'BEXP', 'HK', 'ETRD', 'ETTC']},
       '06HOCHIMINHCITY917': {'date': {'month': 'AUG', 'year': '2006'},
                              'entity_involved': ['RUEHC/SECSTATE WASHDC PRIORITY', 'RUCNARF', 'RUEHHM/AMCONSUL HO',
                                                  'PHUM PGOV PREF KIRF', 'Consul General', 'State',
                                                  'the Montagnard Foundation', 'ConGen', 'GVN',
                                                  'Southern Evangelical Church of Vietnam', 'Dak Nong', 'SBU',
                                                  'Vietnamese Embassy', 'PNTR', 'Congress', 'WINNICK'],
                              'from': 'AMCONSUL HO CHI MINH CITY',
                              'keywords': ['subject', 'migrants', 'congress', 'collective', 'leader'],
                              'most_common_words': [('police', 12), ('ethnic', 7), ('minority', 7), ('Adrong', 7),
                                                    ('contact', 7), ('province', 6), ('HCMC', 5), ('United', 5),
                                                    ('States', 5), ('Central', 5), ('Highlands', 5), ('SECV', 5),
                                                    ('contacts', 4)],
                              'people_involved': ['RUEHCHI RUEHDT RUEHNH', 'HO CHI MINH CITY', '000917 ', 'SIPDIS ',
                                                  'E.O.', 'DECL', 'Seth Winnick', 'Y Ngo Adrong', 'Adrong', 'Siu Y Kim',
                                                  'Gia Lai', 'Chu Se', 'Kim', 'Dega', 'Phu Yen'],
                              'place_involved': ['CENTRAL HIGHLANDS', 'HCMC', 'UNITED STATES', 'DAK LAK', 'CAMBODIA',
                                                 'VIETNAM', 'WASHINGTON'], 'place_of_document': 'HOCHIMINHCITY',
                              'subject': 'POLICE BRUTALITY RISING; CENTRAL HIGHLANDS DEATH CONFIRMED ',
                              'tags': ['PHUM', 'PGOV', 'PREF', 'KIRF', 'VM']},
       '06JERUSALEM906': {'date': {'month': 'MAR', 'year': '2006'},
                          'entity_involved': ['RUEHC/SECSTATE WASHDC', '0698', 'RHEHNSC', 'NSC', 'RUEHBS/USEU BRUSSELS',
                                              'FRONT OFFICE', 'NEA/IPA', 'WILLIAMS/GREENE/WAECHTER', 'ABRAMS',
                                              'PHUM PREF EAID ECON', 'SBU', 'the World Food Program', 'WFP', 'ECON',
                                              'the PA Ministry of National Economy', 'UNRWA', 'Market Monitoring'],
                          'from': 'AMCONSUL JERUSALEM',
                          'keywords': ['subject', 'vulnerability', 'collective', 'works', 'phum'],
                          'most_common_words': [('days', 11), ('food', 7), ('IMMEDIATE', 5), ('Gaza', 5), ('price', 5),
                                                ('flour', 4), ('WASHDC', 3), ('WFP', 3), ('March', 3), ('Karni', 3),
                                                ('stocks', 3), ('report', 3), ('percent', 3), ('JERUSALEM', 2)],
                          'people_involved': ['000906 ', 'SIPDIS ', 'NEA', 'DORAN', 'MUSTAFA ', 'Arnold Vercken',
                                              'Karni'], 'place_involved': ['GAZA', 'WEST BANK/GAZA COUNTRY', 'U.S.'],
                          'place_of_document': 'JERUSALEM', 'subject': 'KARNI CLOSURE CAUSING FOOD SHORTAGE IN GAZA ',
                          'tags': ['PHUM', 'PREF', 'EAID', 'ECON', 'KWBG']},
       '09BERLIN831': {'date': {'month': 'JUL', 'year': '2009'},
                       'entity_involved': ['RUEHC/SECSTATE WASHDC', 'RUEHAD', 'AMEMBASSY ABU DHABI', 'RUEHUJA',
                                           'AMEMBASSY ABUJA PRIORITY', 'RUEHAK', 'AMEMBASSY ANKARA', 'RUEHTH',
                                           'AMEMBASSY ATHENS', 'RUEHBS/', 'AMEMBASSY', 'RUEHEG', 'AMEMBASSY CAIRO',
                                           'RUEHBY', 'AMEMBASSY CANBERRA', 'RUEHCP', 'AMEMBASSY COPENHAGEN', 'RUEHDJ',
                                           'RUEHKL', 'AMEMBASSY KUALA LUMPUR', 'RUEHLI', 'AMEMBASSY LONDON', 'RUEHMD',
                                           'RUEHMV', 'AMEMBASSY MONROVIA', 'RUEHMO', 'RUEHMS/AMEMBASSY MUSCAT',
                                           'RUEHNR', 'AMEMBASSY NAIROBI', 'RUEHNE', 'AMEMBASSY NEW DELHI', 'RUEHNY',
                                           'AMEMBASSY OSLO', 'RUEHOT', 'AMEMBASSY OTTAWA', 'RUEHZP', 'AMEMBASSY PANAMA',
                                           'RUEHFR', 'AMEMBASSY PARIS', 'RUEHRH', 'AMEMBASSY RIYADH', 'RUEHRO',
                                           'RUEHYN', 'RUEHGP/AMEMBASSY SINGAPORE', 'RUEHSM', 'AMEMBASSY STOCKHOLM',
                                           'RUEHTC', 'RUEHKO/AMEMBASSY TOKYO', 'RUCNDT/USMISSION', 'EWWT', 'PHSA',
                                           'PHUM PREL', 'GM', 'CGPCS', 'ON PARTICIPATION ISSUE',
                                           'MFA UN Security Council Action', 'the Contact Group for Piracy', 'Turkish',
                                           'German', 'the International Criminal Tribunal'], 'from': 'AMEMBASSY BERLIN',
                       'keywords': ['subject', 'expertise', 'stockhausen', '091715z', 'ruehul'],
                       'most_common_words': [('AMEMBASSY', 32), ('PRIORITY', 32), ('Germany', 5), ('national', 5),
                                             ('Stockhausen', 4), ('said', 4), ('cases', 4), ('region', 4),
                                             ('BERLIN', 3), ('CGPCS', 3), ('U.S.', 3), ('countries', 3), ('piracy', 3)],
                       'people_involved': ['RUEHBJ', '0210RUEHLO/', 'SIPDIS ', 'E.O.', 'DECL', 'STAN OTTO',
                                           'Dirk Stockhausen', 'Koenig'],
                       'place_involved': ['BRUSSELS', 'MOSCOW', 'HAGUE', 'NEW YORK', 'BERLIN', 'GERMANY', 'U.S.',
                                          'SOMALIA', 'NETHERLANDS', 'KENYA', 'CAMBODIA', 'ARUSHA', 'TANZANIA',
                                          'RWANDA'], 'place_of_document': 'BERLIN',
                       'subject': 'CGPCS: GERMANY AGREES ON PARTICIPATION ISSUE, BUT  IS STILL ' 'OFFSIDE REGARDING '
                                  'INTERNATIONAL '  'TRIBUNAL ',
                       'tags': ['EWWT', 'MARR', 'PGOV', 'PHSA', 'PHUM', 'PREL', 'MOPS', 'GM']}}
